{"timestamp":"2025-05-23T01:08:16.004710","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-23T01:08:16.005292","level":"info","event":"Filling up the DagBag from /home/duc/data-pipeplipe-test/dags/youtube_pipepline_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-23T01:08:19.935245Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:19.935354Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:19.935411Z","level":"info","event":"Current task name:process_frames","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:19.935457Z","level":"info","event":"Dag name:youtube_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:20.542350","level":"warning","event":"You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour","category":"UserWarning","filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/torch/hub.py","lineno":330,"logger":"py.warnings"}
{"timestamp":"2025-05-23T01:08:21.049303Z","level":"error","event":"2025-05-23 08:08:21,049 - src.utils.error_handler - ERROR - Exception occurred: HTTP Error 404: Not Found","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-23T01:08:21.049303","level":"error","event":"Exception occurred: HTTP Error 404: Not Found","logger":"src.utils.error_handler"}
{"timestamp":"2025-05-23T01:08:21.049404","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"HTTPError","exc_value":"HTTP Error 404: Not Found","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/duc/data-pipeplipe-test/src/processors/frame_processor.py","lineno":51,"name":"process_frames"},{"filename":"/home/duc/data-pipeplipe-test/src/utils/error_handler.py","lineno":8,"name":"handle_error"},{"filename":"/home/duc/data-pipeplipe-test/src/processors/frame_processor.py","lineno":16,"name":"process_frames"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/torch/hub.py","lineno":638,"name":"load"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/torch/hub.py","lineno":258,"name":"_get_cache_or_reload"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/torch/hub.py","lineno":203,"name":"_validate_not_a_forked_repo"},{"filename":"/home/duc/.python_envs/global_env/lib/python3.12/site-packages/torch/hub.py","lineno":185,"name":"_read_url"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":215,"name":"urlopen"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":521,"name":"open"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":630,"name":"http_response"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":559,"name":"error"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":492,"name":"_call_chain"},{"filename":"/usr/lib/python3.12/urllib/request.py","lineno":639,"name":"http_error_default"}]}]}
{"timestamp":"2025-05-23T01:08:21.068838Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:21.068901Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:21.068948Z","level":"info","event":"Task:<Task(PythonOperator): process_frames>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-23T01:08:21.068991Z","level":"info","event":"Failure caused by HTTP Error 404: Not Found","chan":"stdout","logger":"task"}
